try {
  function1();
} catch {
  console.log('Esto es un error');
}